package takdevx.dependencyguard

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.internal.artifacts.ivyservice.ivyresolve.VersionInfo
import org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionComparator
import org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionParser
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity.RELATIVE
import org.gradle.api.tasks.TaskAction
import takdevx.dependencyguard.internal.TAKDEVX_TASK_GROUP
import java.io.File

/**
 * Gradle task that validates resolved dependencies against TAK version restrictions.
 *
 * This task reads the dependency guard baseline files (generated by Dropbox's dependency-guard plugin) and compares
 * the resolved dependency versions against maximum allowed versions specified in a restrictions file. Any versions
 * that exceed the limits are reported to a report file and cause the build to fail.
 *
 * The task uses Gradle's internal [DefaultVersionComparator] to handle semantic versioning correctly, including
 * pre-release versions and metadata.
 *
 * Generated report file: `build/reports/tak-dependency-guard.txt`
 *
 * @see DownloadFile
 * @see TakDependencyGuardExtension
 */
@CacheableTask
public abstract class CheckDependencies : DefaultTask() {
  /**
   * Directory containing dependency guard baseline files generated by the Dropbox dependency-guard plugin.
   *
   * These files contain resolved dependency versions for each Gradle configuration (e.g., "classpath.txt").
   * Each file contains lines in format: `group:artifact:version`
   *
   * This directory is typically located at `dependencies/` (relative to project root).
   */
  @get:InputDirectory
  @get:PathSensitive(RELATIVE)
  public abstract val guardFileDir: DirectoryProperty

  /**
   * Path to the restrictions file specifying maximum allowed dependency versions.
   *
   * File format: Each line contains `group:artifact:maxVersion`
   *
   * Example:
   * ```
   * androidx.core:core:1.17.0
   * androidx.fragment:fragment:1.8.9
   * ```
   *
   * This file is either:
   * - Downloaded from GitHub (via [DownloadFile] task)
   * - Loaded from a custom URL
   * - Provided as a local file
   *
   * @see TakDependencyGuardExtension
   */
  @get:InputFile
  @get:PathSensitive(RELATIVE)
  public abstract val restrictionsFile: RegularFileProperty

  /**
   * Output file containing validation report and any detected violations.
   *
   * Report format:
   * ```
   * classpath
   * group:artifact - version (actual) > maxVersion (limit)
   *
   * runtimeClasspath
   * ...
   * ```
   *
   * Default location: `build/reports/takdevx.txt`
   */
  @get:OutputFile
  public abstract val reportFile: RegularFileProperty

  init {
    group = TAKDEVX_TASK_GROUP
    description = "Verifies that no project dependencies exceed those for the specified ATAK version"
  }

  @TaskAction
  public fun execute() {
    val guardFileDir = guardFileDir.get().asFile
    val restrictionsFile = restrictionsFile.get().asFile
    val reportFile = reportFile.get().asFile
    reportFile.delete()

    if (!guardFileDir.exists()) error("$guardFileDir doesn't exist")
    if (!restrictionsFile.exists()) error("$restrictionsFile doesn't exist")

    val restrictions = restrictionsFile.readVersions()
    val reportItems = mutableMapOf<String, List<String>>()
    var hasAnyFailures = false

    guardFileDir
      .listFiles()
      .ifEmpty { error("No dependency guard files found in ${guardFileDir.absolutePath}") }
      .forEach { file ->
        val fileReportItems = mutableListOf<String>()
        logger.info("Checking classpath file $file")
        for ((id, version) in file.readVersions()) {
          val maxVersion = restrictions[id] ?: continue
          if (version > maxVersion) {
            fileReportItems += "$id:$version > $maxVersion"
            hasAnyFailures = true
          }
        }
        reportItems[file.nameWithoutExtension] = fileReportItems
        logger.info("Found ${fileReportItems.size} problems in $file")
      }

    reportFile.printWriter().use { writer ->
      reportItems.forEach { (filename, items) ->
        writer.appendLine(filename)
        items.forEach(writer::appendLine)
        writer.appendLine()
      }
    }

    if (hasAnyFailures) {
      error(
        buildString {
          appendLine("Failed TAK dependency validations - check $reportFile")
          reportItems.forEach { appendLine("  $it") }
        },
      )
    }
  }

  private fun File.readVersions(): Map<String, Version> = bufferedReader().use { reader ->
    reader
      .lineSequence()
      .map { it.trim() }
      .associate { line ->
        val (group, artifact, version) = line.split(":")
        "$group:$artifact" to Version(version)
      }.also { versions -> if (versions.isEmpty()) error("No versions found in $absolutePath") }
  }

  @JvmInline
  private value class Version(val value: String) : Comparable<Version> {
    override fun toString(): String = value

    override fun compareTo(other: Version): Int = comparator.compare(
      VersionInfo(parser.transform(value)),
      VersionInfo(parser.transform(other.value)),
    )

    private companion object {
      private val comparator = DefaultVersionComparator()
      private val parser = VersionParser()
    }
  }
}
